# SwiftLint Configuration for WorkoutTrackerApp

# Rules to include
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces

# Rules to disable
disabled_rules:
  - trailing_whitespace # Can be noisy
  - todo # TODOs are sometimes acceptable during development

# Custom rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ID
    - x
    - y
    - z

nesting:
  type_level:
    warning: 2
    error: 3

# Paths to exclude from linting
excluded:
  - fastlane
  - vendor
  - build
  - DerivedData
  - .build
  - Tests
  - docs
  - ci_logs

# Reporter type
reporter: "xcode"

# Warnings become errors in CI
strict: false
