-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglRXX3nMzOVyyWyrx
wXfqL4foZifTIUa2BsdyX9buMiagCgYIKoZIzj0DAQehRANCAATjfOelW1mmUdK+
Xsr8nFPVqC3Q4w4xuTdswEgK5QP4bzANojRHLI2HJa0HkfgVxSRhKhIsj/zUEkpe
LZkpuPhV
-----END PRIVATE KEY-----