workflows:
  ios_testflight:
    name: iOS TestFlight
    max_build_duration: 60
    environment:
      xcode: "16.0"
      groups:
        - asc_api_key
      vars:
        SCHEME: WorkoutTrackerApp
        BUNDLE_ID: com.kje7713.WorkoutTrackerApp
        APPLE_TEAM_ID: 3W77JDM5X2
    scripts:
      - name: Set up code signing
        script: |
          set -euxo pipefail
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Install XcodeGen
        script: |
          set -euxo pipefail
          brew install xcodegen
          
      - name: Generate Xcode project
        script: |
          set -euxo pipefail
          xcodegen generate
          
      - name: Build and archive
        script: |
          set -euxo pipefail
          xcodebuild \
            -project WorkoutTrackerApp.xcodeproj \
            -scheme "$SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            -allowProvisioningUpdates \
            clean archive
            
      - name: Export IPA
        script: |
          set -euxo pipefail
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>automatic</string>
            <key>teamID</key><string>$APPLE_TEAM_ID</string>
          </dict>
          </plist>
          EOF
          
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath "$CM_BUILD_DIR"
            
    artifacts:
      - $CM_BUILD_DIR/*.ipa
      
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
