workflows:
  ios_testflight:
    name: iOS TestFlight (robust)
    max_build_duration: 60

    environment:
      xcode: 16.0
      groups:
        - ios_config          # must include: DEVELOPMENT_TEAM=3W77JDM5X2 (and optionally BUNDLE_ID)
        - asc_api_key         # must include: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY
      vars:
        SCHEME: WorkoutTrackerApp
        BUNDLE_ID: com.kje7713.WorkoutTrackerApp
        DEVELOPMENT_TEAM: 3W77JDM5X2

    cache:
      cache_paths:
        - $HOME/Library/Developer/Xcode/DerivedData
        - $HOME/Library/Caches/org.swift.swiftpm

    scripts:
      - name: Validate XcodeGen spec
        script: |
          set -euxo pipefail
          if [ ! -f project.yml ] && [ ! -f project.yaml ]; then
            echo "ERROR: project.yml not found in repo root."
            ls -la
            exit 2
          fi
          head -n 30 project.yml || true
          if ! grep -qE '^[[:space:]]*name:[[:space:]]' project.yml; then
            echo "ERROR: project.yml missing required 'name:'"
            exit 3
          fi

      - name: Install XcodeGen (safe fallback)
        script: |
          set -euxo pipefail
          echo "Downloading XcodeGen..."
          curl -Ls https://github.com/yonaskolb/XcodeGen/releases/latest/download/xcodegen.zip -o xcodegen.zip
          rm -rf "$HOME/xcodegen_bin"
          mkdir -p "$HOME/xcodegen_bin"
          unzip -qo xcodegen.zip -d "$HOME/xcodegen_bin"
          chmod +x "$HOME/xcodegen_bin/xcodegen"
          # Persist PATH for subsequent steps
          echo 'export PATH="$HOME/xcodegen_bin:$PATH"' >> $CM_ENV
          # Also available in this step
          export PATH="$HOME/xcodegen_bin:$PATH"
          which xcodegen
          xcodegen version

      - name: Generate Xcode project
        script: |
          set -euxo pipefail
          xcodegen generate

      - name: Build & archive
        script: |
          set -euxo pipefail
          xcodebuild \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/WorkoutTrackerApp.xcarchive" \
            -sdk iphoneos \
            clean archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates

      - name: Create ExportOptions.plist
        script: |
          cat > "$CM_BUILD_DIR/ExportOptions.plist" << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
            <key>destination</key>
            <string>export</string>
          </dict>
          </plist>
          EOF

      - name: Export .ipa
        script: |
          set -euxo pipefail
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/WorkoutTrackerApp.xcarchive" \
            -exportPath "$CM_BUILD_DIR/export" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist"

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/WorkoutTrackerApp.xcarchive