//
//  PaywallView.swift
//  Savage By Design
//
//  Subscription paywall view with trial offer
//

import SwiftUI

/// Paywall view for presenting subscription offer
struct PaywallView: View {
    @EnvironmentObject private var subscriptionManager: SubscriptionManager
    @Environment(\.dismiss) private var dismiss
    @Environment(\.colorScheme) private var colorScheme
    @Environment(\.sbdTheme) private var theme
    
    @State private var isPurchasing = false
    @State private var isEligibleForTrial = true
    
    var body: some View {
        NavigationView {
            ScrollView {
                VStack(spacing: 32) {
                    
                    // MARK: - Header
                    
                    headerSection
                    
                    // MARK: - Features List
                    
                    featuresSection
                    
                    // MARK: - Pricing & CTA
                    
                    pricingSection
                    
                    // MARK: - Legal & Links
                    
                    legalSection
                    
                    Spacer(minLength: 20)
                }
                .padding(.horizontal, 24)
                .padding(.top, 32)
            }
            .background(backgroundColor.ignoresSafeArea())
            .navigationTitle("Go Pro")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    Button("Close") {
                        dismiss()
                    }
                }
            }
            .task {
                // Check trial eligibility when view appears
                isEligibleForTrial = await subscriptionManager.checkIntroOfferEligibility()
            }
        }
    }
    
    // MARK: - Header Section
    
    private var headerSection: some View {
        VStack(spacing: 16) {
            Image(systemName: "flame.fill")
                .font(.system(size: 60))
                .foregroundColor(theme.premiumGradientEnd)
            
            Text("Unlock Pro Import Tools")
                .font(.system(size: 28, weight: .bold))
                .multilineTextAlignment(.center)
            
            Text("Import and parse AI-generated workout plans from JSON")
                .font(.system(size: 16, weight: .regular))
                .foregroundColor(theme.mutedText)
                .multilineTextAlignment(.center)
        }
    }
    
    // MARK: - Features Section
    
    private var featuresSection: some View {
        VStack(alignment: .leading, spacing: 20) {
            
            FeatureRow(
                icon: "brain.head.profile",
                title: "AI Powered Exercise & Block Building",
                description: "Generate customized workout blocks and exercises using AI assistance"
            )
            
            FeatureRow(
                icon: "sparkles",
                title: "AI Powered Experience Engineering",
                description: "From training, to learning, to planning a day at the theme park - AI adapts to your life"
            )
            
            FeatureRow(
                icon: "rectangle.portrait.on.rectangle.portrait",
                title: "Whiteboard View",
                description: "When you want to train or move, not doom scroll"
            )
            
            FeatureRow(
                icon: "doc.text.fill",
                title: "AI-Assisted Plan Ingestion",
                description: "Import and parse workout plans from JSON files generated by ChatGPT, Claude, or any AI assistant"
            )
            
            FeatureRow(
                icon: "list.bullet.clipboard",
                title: "AI Prompt Templates",
                description: "Copy-paste ready prompts for generating structured workout blocks"
            )
        }
    }
    
    // MARK: - Pricing Section
    
    private var pricingSection: some View {
        VStack(spacing: 16) {
            
            // Trial badge
            if isEligibleForTrial {
                Text("START FREE TRIAL")
                    .font(.system(size: 14, weight: .bold))
                    .foregroundColor(.white)
                    .padding(.horizontal, 20)
                    .padding(.vertical, 8)
                    .background(Color.green)
                    .cornerRadius(20)
            }
            
            // Pricing card
            VStack(spacing: 12) {
                if let price = subscriptionManager.formattedPrice {
                    Text(price)
                        .font(.system(size: 48, weight: .bold))
                    
                    if isEligibleForTrial {
                        Text("Free trial, then \(price)")
                            .font(.system(size: 14, weight: .regular))
                            .foregroundColor(theme.mutedText)
                            .multilineTextAlignment(.center)
                    }
                }
            }
            .padding(.vertical, 24)
            .frame(maxWidth: .infinity)
            .background(
                RoundedRectangle(cornerRadius: 16)
                    .fill(colorScheme == .dark ? Color.white.opacity(0.1) : Color.black.opacity(0.05))
            )
            
            // Subscribe button
            Button {
                Task {
                    isPurchasing = true
                    let success = await subscriptionManager.purchase()
                    isPurchasing = false
                    
                    // Dismiss on successful purchase
                    if success {
                        dismiss()
                    }
                }
            } label: {
                HStack {
                    if isPurchasing {
                        ProgressView()
                            .progressViewStyle(CircularProgressViewStyle(tint: .white))
                    } else {
                        Text(isEligibleForTrial ? "Start Free Trial" : "Subscribe Now")
                            .font(.system(size: 18, weight: .bold))
                    }
                }
                .frame(maxWidth: .infinity)
                .frame(height: 56)
                .foregroundColor(.white)
                .background(
                    Group {
                        if subscriptionManager.subscriptionProduct == nil {
                            Color.gray
                        } else {
                            LinearGradient(
                                gradient: Gradient(colors: [theme.premiumGradientStart, theme.premiumGradientEnd]),
                                startPoint: .leading,
                                endPoint: .trailing
                            )
                        }
                    }
                )
                .cornerRadius(28)
                .shadow(
                    color: subscriptionManager.subscriptionProduct == nil
                        ? Color.clear
                        : theme.premiumGradientStart.opacity(0.3),
                    radius: 8,
                    x: 0,
                    y: 4
                )
            }
            .disabled(isPurchasing || subscriptionManager.subscriptionProduct == nil)
            
            // Error message display
            if let error = subscriptionManager.errorMessage {
                Text(error)
                    .font(.system(size: 14, weight: .medium))
                    .foregroundColor(.red)
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, 16)
            }
            
            // Loading indicator when product is being loaded
            if subscriptionManager.subscriptionProduct == nil && subscriptionManager.errorMessage == nil {
                HStack(spacing: 8) {
                    ProgressView()
                        .progressViewStyle(CircularProgressViewStyle())
                    Text("Loading subscription information...")
                        .font(.system(size: 14, weight: .regular))
                        .foregroundColor(theme.mutedText)
                }
            }
            
            // Restore button
            Button {
                Task {
                    await subscriptionManager.restorePurchases()
                }
            } label: {
                Text("Restore Purchases")
                    .font(.system(size: 16, weight: .medium))
                    .foregroundColor(theme.accent)
            }
            .padding(.top, 8)
            
            // Auto-renew disclosure
            Text("Subscription automatically renews unless cancelled at least 24 hours before the end of the current period.")
                .font(.system(size: 12, weight: .regular))
                .foregroundColor(theme.mutedText)
                .multilineTextAlignment(.center)
                .padding(.top, 8)
        }
    }
    
    // MARK: - Legal Section
    
    private var legalSection: some View {
        HStack(spacing: 20) {
            Link("Privacy Policy", destination: URL(string: SubscriptionConstants.privacyPolicyURL)!)
                .font(.system(size: 14, weight: .medium))
                .foregroundColor(theme.accent)
            
            Text("•")
                .foregroundColor(theme.mutedText)
            
            Link("Terms of Service", destination: URL(string: SubscriptionConstants.termsOfServiceURL)!)
                .font(.system(size: 14, weight: .medium))
                .foregroundColor(theme.accent)
        }
    }
    
    // MARK: - Helpers
    
    private var backgroundColor: Color {
        colorScheme == .dark ? theme.backgroundDark : theme.backgroundLight
    }
}

// MARK: - Feature Row

struct FeatureRow: View {
    let icon: String
    let title: String
    let description: String
    
    @Environment(\.colorScheme) private var colorScheme
    @Environment(\.sbdTheme) private var theme
    
    var body: some View {
        HStack(alignment: .top, spacing: 16) {
            Image(systemName: icon)
                .font(.system(size: 24))
                .foregroundColor(theme.premiumGradientStart)
                .frame(width: 32)
            
            VStack(alignment: .leading, spacing: 4) {
                Text(title)
                    .font(.system(size: 16, weight: .semibold))
                
                Text(description)
                    .font(.system(size: 14, weight: .regular))
                    .foregroundColor(theme.mutedText)
            }
        }
    }
}

// MARK: - Preview

struct PaywallView_Previews: PreviewProvider {
    static var previews: some View {
        PaywallView()
            .environmentObject(SubscriptionManager())
    }
}
