name: WorkoutTrackerApp

options:
  bundleIdPrefix: com.kje7713
  deploymentTarget:
    iOS: "17.0"
  generateEmptyDirectories: false
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: 5.10
    IPHONEOS_DEPLOYMENT_TARGET: 17.0

targets:
  WorkoutTrackerApp:
    type: application
    platform: iOS
    productName: WorkoutTrackerApp
    bundleId: com.kje7713.WorkoutTrackerApp
    sources:
      - path: .
        includes:
          - ContentView.swift
          - Models.swift
          - WorkoutTrackerAppApp.swift
          - Info.plist
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"  # iPhone, iPad
    scheme:
      testTargets: []
      gatherCoverageData: false