name: WorkoutTrackerApp

options:
  bundleIdPrefix: com.kje7713
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "16.4"

targets:
  WorkoutTrackerApp:
    type: application
    platform: iOS
    bundleId: com.kje7713.WorkoutTrackerApp
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: WorkoutTrackerApp
        UILaunchScreen: {}
    sources:
      - path: .
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kje7713.WorkoutTrackerApp
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0