name: YourAppName

options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    DEVELOPMENT_TEAM: ${APPLE_TEAM_ID}
    CODE_SIGN_STYLE: Manual

targets:
  YourAppName:
    type: application
    platform: iOS

    info:
      path: Info.plist
      properties:
        CFBundleIdentifier: ${APP_IDENTIFIER}

        # ✅ REQUIRED — ensures launch screen key is in the generated Info.plist
        UILaunchStoryboardName: LaunchScreen

        # ✅ LOCK ORIENTATIONS so XcodeGen can't strip them
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

    sources:
      - path: .
        includes:
          - "*.swift"
          - "Assets.xcassets"
        excludes:
          - "fastlane/**"
          - "ci_logs/**"
          - "vendor/**"
          - ".git/**"
          - ".github/**"
          - "*.md"
          - "*.rb"
          - "*.yml"
          - "Gemfile*"
          - "AuthKey*.p8"

    # ✅ NEW — LaunchScreen.storyboard must be a RESOURCE (not a source)
    resources:
      - path: .
        includes:
          - "LaunchScreen.storyboard"

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${APP_IDENTIFIER}
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Distribution"