name: YourAppName

options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    # 👇 THIS FIXES YOUR ERROR (Fastlane reads it after xcodegen)
    DEVELOPMENT_TEAM: ${APPLE_TEAM_ID}
    CODE_SIGN_STYLE: Manual

targets:
  YourAppName:
    type: application
    platform: iOS
    sources:
      - path: .
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${APP_IDENTIFIER}
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Distribution"