name: YourAppName

options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    DEVELOPMENT_TEAM: ${APPLE_TEAM_ID}
    CODE_SIGN_STYLE: Manual
    CURRENT_PROJECT_VERSION: "1"
    MARKETING_VERSION: "1.0"

targets:
  YourAppName:
    type: application
    platform: iOS
    
    preBuildScripts:
      - name: Embed Git Branch
        script: |
          # Get the current git branch name
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
          echo "Build branch: $BRANCH_NAME"
          
          # Update Info.plist with branch name
          /usr/libexec/PlistBuddy -c "Delete :BUILD_BRANCH" "${INFOPLIST_FILE}" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :BUILD_BRANCH string $BRANCH_NAME" "${INFOPLIST_FILE}"

    info:
      path: Info.plist
      properties:
        CFBundleIdentifier: ${APP_IDENTIFIER}
        CFBundleDisplayName: "Killin' It"

        # ✅ REQUIRED FOR APP STORE / iPAD MULTITASKING
        UILaunchStoryboardName: LaunchScreen

        # ✅ LOCK ORIENTATIONS so XcodeGen can't strip them
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

    sources:
      - path: .
        includes:
          - "*.swift"
          - "Assets.xcassets"
          - "LaunchScreen.storyboard"   # ✅ ADDED: ensures launch screen is bundled
        excludes:
          - "fastlane/**"
          - "ci_logs/**"
          - "vendor/**"
          - ".git/**"
          - ".github/**"
          - "*.md"
          - "*.rb"
          - "*.yml"
          - "Gemfile*"
          - "AuthKey*.p8"

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${APP_IDENTIFIER}
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Distribution"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"