name: WorkoutTrackerApp

options:
  bundleIdPrefix: com.kje7713
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    DEVELOPMENT_TEAM: ${APPLE_TEAM_ID}
    CODE_SIGN_STYLE: Manual
    CURRENT_PROJECT_VERSION: "1"
    MARKETING_VERSION: "1.0"

targets:
  WorkoutTrackerApp:
    type: application
    platform: iOS
    
    preBuildScripts:
      - name: Embed Git Branch
        script: |
          # Get the current git branch name
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
          echo "Build branch: $BRANCH_NAME"
          
          # Update Info.plist with branch name
          /usr/libexec/PlistBuddy -c "Delete :BUILD_BRANCH" "${INFOPLIST_FILE}" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :BUILD_BRANCH string $BRANCH_NAME" "${INFOPLIST_FILE}"
        outputFiles:
          - "${INFOPLIST_FILE}"

    info:
      path: Info.plist
      properties:
        CFBundleIdentifier: ${APP_IDENTIFIER}
        CFBundleDisplayName: "SBD"

        # ✅ iPhone-only app (UIDeviceFamily: 1 = iPhone only)
        UIDeviceFamily:
          - 1

        # ✅ REQUIRED FOR APP STORE
        UILaunchStoryboardName: LaunchScreen

        # ✅ iPhone orientations (all supported)
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

    sources:
      - path: .
        includes:
          - "*.swift"
          - "Assets.xcassets"
          - "LaunchScreen.storyboard"   # ✅ ADDED: ensures launch screen is bundled
          - "PrivacyInfo.xcprivacy"     # ✅ ADDED: iOS 17+ privacy manifest
        excludes:
          - "Tests/**"                   # Exclude all test files from main target
          - "*Test*.swift"               # Exclude test files at root level
          - "TestRunner.swift"           # Exclude test runner
          - "fastlane/**"
          - "ci_logs/**"
          - "vendor/**"
          - ".git/**"
          - ".github/**"
          - "*.md"
          - "*.rb"
          - "*.yml"
          - "Gemfile*"
          - "AuthKey*.p8"
          - "docs/**"

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${APP_IDENTIFIER}
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Distribution"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: "wholemodule"

schemes:
  WorkoutTrackerApp:
    build:
      targets:
        WorkoutTrackerApp: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: false
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release