name: WorkoutTrackerApp

options:
  bundleIdPrefix: com.kje7713
  deploymentTarget:
    iOS: "15.0"

targets:
  WorkoutTrackerApp:
    type: application
    platform: iOS
    bundleId: com.kje7713.WorkoutTrackerApp
    sources:
      - path: .
        excludes:
          - vendor/**
          - fastlane/**
          - Gemfile
          - Gemfile.lock
          - project.yml
          - README.md
          - "*.rb"
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: WorkoutTrackerApp
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kje7713.WorkoutTrackerApp
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0