name: WorkoutTrackerApp

options:
  bundleIdPrefix: com.kje7713
  deploymentTarget:
    iOS: "17.0"
  generateEmptyDirectories: false
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: 5.10
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    ALWAYS_SEARCH_USER_PATHS: NO
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      SWIFT_COMPILATION_MODE: singlefile
      GCC_OPTIMIZATION_LEVEL: 0
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Release:
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE

targets:
  WorkoutTrackerApp:
    type: application
    platform: iOS
    productName: WorkoutTrackerApp
    bundleId: com.kje7713.WorkoutTrackerApp
    sources:
      - path: .
        includes:
          - ContentView.swift
          - Models.swift
          - WorkoutTrackerAppApp.swift
          - Info.plist
          - Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_NAME: WorkoutTrackerApp
        PRODUCT_BUNDLE_IDENTIFIER: com.kje7713.WorkoutTrackerApp
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 3W77JDM5X2   # <- your Apple Team ID
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
    scheme:
      testTargets: []
      gatherCoverageData: false
