default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    match(
      type: "appstore",
      readonly: false,
      git_url: "https://github.com/kje7713-dev/certificates.git",
      git_branch: "main",
      username: ENV["APPLE_ID"],
      team_id: ENV["APPLE_TEAM_ID"],
      git_basic_authorization: Base64.strict_encode64("x-access-token:#{ENV['MATCH_GIT_TOKEN']}")
    )

    build_ios_app(
      scheme: ENV["IOS_SCHEME"]
    )

    upload_to_testflight(
      username: ENV["APPLE_ID"],
      app_identifier: ENV["APP_IDENTIFIER"]
    )
  end
end